### ISSUE TITLE
how is this version different from MSMutect2, except for performance?

### ISSUE THREAD

**Issue by hurrialice** [MaruvkaLab/MSMuTect_0.5#1]
Hi @AvrahamKahan123 and Yosi,

I was trying to run MSMutect on some hg38 WGS pairs from a docker I built with https://github.com/getzlab/MSMuTect2. It is nice to see that you made a more updated version!

I wonder what is changed between the two versions except for performance, especially in terms of the algorithm? Will the updates significantly impact the results (e.g. "Decision"?)

Thanks,
Qing

**Comment by AvrahamKahan123** [comment]
Hi @hurrialice ,
The decision-making process is entirely the same, with two minor exceptions. Firstly, I believe this version may, rarely, catch reads in the Histogram that 2.0 fails to catch. Secondly, this version adds a Fisher Exact test to the mutation calling step of the program. Neither of these should greatly influence your results. 
The more obvious changes are that this is version is:
(a) faster. The degree of the speedup will greatly depend on the distribution of your loci throughout the genome, but I have seen cases where it has reached 30X faster per core
(b) More robust
(c) more flexible and easier to use. For example, with this version, you can select certain steps and skip irrelevant ones. You can install the software using pip.  You can set how many cores you want to use, ranges of loci to analyze, etc. The manual has all the details (or at least most of them. I am working on updating it). 
Link to the manual
https://docs.google.com/document/d/1glEt64Dj0W74n88XrI9GxlUYvrPJ6r7IK8Pbpi-1MWU/
Thanks,
Avraham
